---
- name: Commmon setup for all CloudLab VMs
  hosts: all
  become: true

  vars:
    lab_network: "192.168.0.0/24"
    monitoring_ip: "192.168.0.113"
    app_ip: "192.168.0.110"
    proxy_ip: "192.168.0.111"

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Install common packages
      ansible.builtin.apt:
        name:
          - curl
          - wget
          - git
          - vim
          - htop
          - net-tools
          - unzip
          - ca-certificates
          - gnupg
          - ufw
          - prometheus-node-exporter
        state: present

    - name: Allow SSH from lab network
      community.general.ufw:
        rule: allow
        from_ip: "{{ lab_network }}"
        port: "22"
        proto: tcp

    - name: Allow Nodeexporter from monitoring VM
      community.general.ufw:
        rule: allow
        from_ip: "{{ monitoring_ip }}"
        port: "9100"
        proto: tcp
    
    - name: Set UFW default incoming policy to deny
      community.general.ufw:
        direction: incoming
        policy: deny

    - name: Set UFW default outgoing policy to allow
      community.general.ufw:
        direction: outgoing
        policy: allow

    - name: Enable UFW
      community.general.ufw:
        state: enabled

- name: Configure Nginx reverse proxy
  hosts: proxy
  become: true


  vars:
    lab_network: "192.168.0.0/24"
    app_ip: "192.168.0.110"

  handlers:
    - name: Restart nginx
      ansible.builtin.systemd:
        name: nginx
        state: restarted

  tasks:
    - name: Install Nginx
      ansible.builtin.apt:
        name:
          - nginx
          - fail2ban
        state: present
        update_cache: true
    
    
    - name: Deploy Cloudlab Nginx config
      ansible.builtin.template:
        src: templates/cloudlab.conf.j2
        dest: /etc/nginx/sites-available/cloudlab
        owner: root
        group: root
        mode: "0644"
      notify: Restart Nginx

    - name: Remove default Nginx site
      ansible.builtin.file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      notify: Restart nginx

    - name: Enable CloudLab Nginx site
      ansible.builtin.file:
        src: /etc/nginx/sites-available/cloudlab
        dest: /etc/nginx/sites-enabled/cloudlab
        state: link
      notify: Restart nginx

    - name: Test Nginx configuration
      ansible.builtin.command: nginx -t
      changed_when: false

    - name: Enable and start Nginx
      ansible.builtin.systemd:
        name: nginx
        enabled: true
        state: started

    - name: Enabble and start Fail2ban
      ansible.builtin.systemd:
        name: fail2ban
        enabled: true
        state: started

    - name: Allow HTTP from lab network
      community.general.ufw:
        rule: allow
        from_ip: "{{ lab_network }}"
        port: "80"
        proto: tcp

